[package]
name = "sidecar"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
reqwest =  { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.149", features = ["derive"] }
serde_bytes = "0.11.15"
serde_json = "1.0.120"
